- hosts: local
  tasks:
    #dodanie repo do zabbixa
    #- name: usuwamy repo
    #  shell: rm -rf /etc/yum.repos.d/*
    - name: dodanie EPELA
      yum: 
        name: epel-release 
        state: installed
    - name: install zabbix.repo
      shell: rpm -ivh http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    - name: instalowanie pakietow do zabbixa
      yum: name={{item}} state=installed
      with_items:
        - mariadb-server
        - mariadb
        - httpd
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
    - name: startowanie bazy
      shell: systemctl start mariadb
    - name: dodanie do autostartu
      shell: systemctl enable mariadb
     # Install configuration database permission, import zabbix database
    - name: set mariadb password
      shell: mysqladmin -u root password 'passw0rd'
    - name: create zabbix master databases
      shell: mysql -uroot -ppassw0rd -e 'create database zabbix character set utf8 collate utf8_bin;'
    - name: set zabbix master databases grant
      shell: mysql -uroot -ppassw0rd -e 'grant all privileges on zabbix.* to zabbix@localhost identified by "zabbix";'
    - name: import zabbix initial data SQL shell
      shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix
    - name: edit zabbix dbhost
      lineinfile:
        dest: /etc/zabbix/zabbix_server.conf
        regexp: '# DBHost=localhost'
        line: 'DBHost=localhost'
    - name: edit zabbix dbpasswd
      lineinfile:
        dest: /etc/zabbix/zabbix_server.conf
        regexp: '# DBPassword='
        line: 'DBPassword=zabbix'
    - name: uncomment
      lineinfile:
        dest: /etc/httpd/conf.d/zabbix.conf
        regexp: '# php_value'
        line: 'php_value'
    - name: off selinux
      shell: setenforce 0
    - name: seline modify enforcing
      lineinfile:
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
