- hosts: local
  become: yes
  vars:
    file_dest: "/etc/zabbix/zabbix_agentd.conf"
  tasks:
    - name: dodanie agenta do zabbixa
      yum: 
        name: zabbix-agent
        state: installed
    - name: dodanie serwera do konfiga
      lineinfile:
        dest: "{{ file_dest }}"
        regexp: '# Server='
        line: 'Server=127.0.0.1'
    - name: dodanie aktywnego serwera
      lineinfile:
        dest: "{{ file_dest }}"
        regexp: '# ServerActive='
        line: 'ServerActive=127.0.0.1'
    - name: zmieniamy hosta
      lineinfile:
        dest: "{{ file_dest }}"
        regexp: '# Hostname='
        line: 'Hostname=127.0.0.1'
    - name: start procesu
      systemd:
        state: started
        name: zabbix-agent
      
    #- name: uncomment
    #  replace:
    #    dest: /etc/httpd/conf.d/zabbix.conf
    #    regexp: '# php_value'
    #    replace: 'php_value'
    #- name: Set httpd_can_connect_zabbix flag on and keep it persistent across reboots
    #  seboolean:
    #    name: httpd_can_connect_zabbix
    #    state: yes
    #    persistent: yes
    #- name: off selinux
    #  shell: setenforce 0
    #- name: seline modify enforcing
    #  lineinfile:
    #    dest: /etc/selinux/config
    #    regexp: '^SELINUX='
    #    line: 'SELINUX=disabled'
